name: CI/CD Pipeline for Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Railway CLI
      run: |
        curl -sL https://railway.app/install.sh | bash
        railway --version

    - name: Login to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        echo $RAILWAY_TOKEN | railway login

    - name: Link to the correct Railway project
      run: |
        railway link --project-id 25fe0141-08ce-4675-b39a-55d46fcc4597

    - name: Deploy to Railway
      run: |
        railway up
