name: CI/CD Pipeline for Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Adjust if you have specific tests to run

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: '3.x'

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Add your Railway token in GitHub secrets
      run: |
        curl -sL https://railway.app/install | sh
        railway up
